name: AstralRinth App build

on:
  push:
    branches:
      - main
      - feature*
    tags:
      - 'v*'
    paths:
      - .github/workflows/astralrinth-build.yml
      - 'apps/app/**'
      - 'apps/app-frontend/**'
      - 'packages/app-lib/**'
      - 'packages/app-macros/**'
      - 'packages/assets/**'
      - 'packages/ui/**'
      - 'packages/utils/**'

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-22.04]
        include:
          - platform: macos-latest
            artifact-target-name: universal-apple-darwin
          - platform: windows-latest
            artifact-target-name: x86_64-pc-windows-msvc
          - platform: ubuntu-22.04
            artifact-target-name: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.platform }}

    steps:
      - name: 📥 Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 🧰 Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.artifact-target-name }}

      - name: 🧰 Install pnpm
        uses: pnpm/action-setup@v4

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: 🧰 Install Linux build dependencies
        if: matrix.platform == 'ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get install -yq \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            xdg-utils \
            openjdk-11-jdk

      - name: 💨 Setup Turbo cache
        uses: rharkor/caching-for-turbo@v1.8

      - name: 🧰 Install dependencies
        run: pnpm install

      - name: ✍️ Set up Windows code signing (jsign)
        if: matrix.platform == 'windows' && env.SIGN_WINDOWS_BINARIES == 'true'
        shell: bash
        run: |
          choco install jsign --ignore-dependencies

      - name: 🗑️ Clean up cached bundles
        shell: bash
        run: |
          rm -rf target/release/bundle
          rm -rf target/*/release/bundle || true

      - name: 🔨 Build macOS app
        if: matrix.platform == 'macos-latest'
        run: pnpm --filter=@modrinth/app run tauri build --target universal-apple-darwin --config tauri-release.conf.json
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: 🔨 Build Linux app
        if: matrix.platform == 'ubuntu-22.04'
        run: pnpm --filter=@modrinth/app run tauri build --config tauri-release.conf.json
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: 🔨 Build Windows app
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          $env:JAVA_HOME = "$env:JAVA_HOME_11_X64"
          pnpm --filter=@modrinth/app run tauri build --config tauri-release.conf.json --verbose --bundles 'nsis'
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: 📤 Upload app bundles
        uses: actions/upload-artifact@v3
        with:
          name: App bundle (${{ matrix.artifact-target-name }})
          path: |
            target/release/bundle/**
            target/*/release/bundle/**
